module.exports.getCities = {
    Oregon: [
        { cityName: "Albany" },
        { cityName: "Ashland" },
        { cityName: "Astoria" },
        { cityName: "Baker City" },
        { cityName: "Beaverton" },
        { cityName: "Bend" },
        { cityName: "Brookings" },
        { cityName: "Burns" },
        { cityName: "Canby" },
        { cityName: "Central Point" },
        { cityName: "Clackamas" },
        { cityName: "Coos Bay" },
        { cityName: "Corvallis" },
        { cityName: "Cottage Grove" },
        { cityName: "Dallas" },
        { cityName: "Damascus" },
        { cityName: "Eagle Point" },
        { cityName: "Eugene" },
        { cityName: "Florence" },
        { cityName: "Forest Grove" },
        { cityName: "Grants Pass" },
        { cityName: "Gresham" },
        { cityName: "Happy Valley" },
        { cityName: "Hermiston" },
        { cityName: "Hillsboro" },
        { cityName: "Hood River" },
        { cityName: "Independence" },
        { cityName: "Junction City" },
        { cityName: "Keizer" },
        { cityName: "Klamath Falls" },
        { cityName: "La Grande" },
        { cityName: "Lake Oswego" },
        { cityName: "Lebanon" },
        { cityName: "Madras" },
        { cityName: "McMinnville" },
        { cityName: "Medford" },
        { cityName: "Milton-Freewater" },
        { cityName: "Milwaukie" },
        { cityName: "Molalla" },
        { cityName: "Monmouth" },
        { cityName: "Newberg" },
        { cityName: "Newport" },
        { cityName: "North Bend" },
        { cityName: "Ontario" },
        { cityName: "Oregon City" },
        { cityName: "Pendleton" },
        { cityName: "Philomath" },
        { cityName: "Portland" },
        { cityName: "Prineville" },
        { cityName: "Redmond" },
        { cityName: "Roseburg" },
        { cityName: "Salem" },
        { cityName: "Sandy" },
        { cityName: "Scappoose" },
        { cityName: "Seaside" },
        { cityName: "Sheridan" },
        { cityName: "Sherwood" },
        { cityName: "Silverton" },
        { cityName: "Springfield" },
        { cityName: "St. Helens" },
        { cityName: "Stayton" },
        { cityName: "Sutherlin" },
        { cityName: "Sweet Home" },
        { cityName: "Talent" },
        { cityName: "The Dalles" },
        { cityName: "Tigard" },
        { cityName: "Tillamook" },
        { cityName: "Troutdale" },
        { cityName: "Tualatin" },
        { cityName: "Umatilla" },
        { cityName: "Warrenton" },
        { cityName: "West Linn" },
        { cityName: "Wilsonville" },
        { cityName: "Woodburn" }
    ]
};
