module.exports.getMajors = [
    {majorName: "Accounting"},
    {majorName: "Agricultural and Food Business Management"},
    {majorName: "Agricultural Science"},
    {majorName: "American Studies"},
    {majorName: "Animal Sciences"},
    {majorName: "Anthropology"},
    {majorName: "Apparel Design"},
    {majorName: "Applied Mathematics"},
    {majorName: "Applied Physics"},
    {majorName: "Applied Psychology"},
    {majorName: "Architectural Engineering"},
    {majorName: "Art"},
    {majorName: "Arts, Media and Technology"},
    {majorName: "Biochemistry and Biophysics"},
    {majorName: "Biology"},
    {majorName: "Biomedical Engineering"},
    {majorName: "Business Administration"},
    {majorName: "Business Information Systems"},
    {majorName: "Chemistry"},
    {majorName: "Civil Engineering"},
    {majorName: "Clinical Laboratory Science"},
    {majorName: "Cognitive Science"},
    {majorName: "Communication Studies"},
    {majorName: "Computer Engineering"},
    {majorName: "Computer Science"},
    {majorName: "Construction Engineering"},
    {majorName: "Criminology and Criminal Justice"},
    {majorName: "Crop and Soil Sciences"},
    {majorName: "Earth Science"},
    {majorName: "Economics"},
    {majorName: "Electrical Engineering"},
    {majorName: "Elementary Education"},
    {majorName: "English"},
    {majorName: "Entomology"},
    {majorName: "Environmental Engineering"},
    {majorName: "Environmental Science"},
    {majorName: "Exercise Science"},
    {majorName: "Family and Consumer Sciences"},
    {majorName: "Finance"},
    {majorName: "Fisheries and Wildlife"},
    {majorName: "Food Science and Technology"},
    {majorName: "French"},
    {majorName: "Geography"},
    {majorName: "Geology"},
    {majorName: "German"},
    {majorName: "Global Studies"},
    {majorName: "Graphic Design"},
    {majorName: "History"},
    {majorName: "Human Development and Family Sciences"},
    {majorName: "Human Nutrition"},
    {majorName: "Industrial Engineering"},
    {majorName: "Information Systems"},
    {majorName: "Integrated Studies"},
    {majorName: "Interior Design"},
    {majorName: "Italian"},
    {majorName: "Kinesiology"},
    {majorName: "Landscape Architecture"},
    {majorName: "Latin"},
    {majorName: "Liberal Studies"},
    {majorName: "Linguistics"},
    {majorName: "Management"},
    {majorName: "Marketing"},
    {majorName: "Mathematics"},
    {majorName: "Mechanical Engineering"},
    {majorName: "Medical Laboratory Science"},
    {majorName: "Microbiology"},
    {majorName: "Music"},
    {majorName: "Natural Resources Conservation and Management"},
    {majorName: "Nursing"},
    {majorName: "Nutrition and Dietetics"},
    {majorName: "Philosophy"},
    {majorName: "Physics"},
    {majorName: "Plant and Soil Science"},
    {majorName: "Political Science"},
    {majorName: "Portuguese"},
    {majorName: "Psychology"},
    {majorName: "Public Administration"},
    {majorName: "Public Health"},
    {majorName: "Real Estate"},
    {majorName: "Recreation Management"},
    {majorName: "Religious Studies"},
    {majorName: "Russian"},
    {majorName: "Science, Technology, and Society"},
    {majorName: "Spanish"},
    {majorName: "Speech Communication"},
    {majorName: "Statistics"},
    {majorName: "Theatre Arts"},
    {majorName: "Urban and Regional Planning"},
    {majorName: "Wildlife Science"},
    {majorName: "Women and Gender Studies"}
];

