module.exports.getStates = {
    USA: [
        { stateName: "Alaska" },
        { stateName: "Alabama" },
        { stateName: "Arkansas" },
        { stateName: "American Samoa" },
        { stateName: "Arizona" },
        { stateName: "California" },
        { stateName: "Colorado" },
        { stateName: "Connecticut" },
        { stateName: "District of Columbia" },
        { stateName: "Delaware" },
        { stateName: "Florida" },
        { stateName: "Georgia" },
        { stateName: "Guam" },
        { stateName: "Hawaii" },
        { stateName: "Iowa" },
        { stateName: "Idaho" },
        { stateName: "Illinois" },
        { stateName: "Indiana" },
        { stateName: "Kansas" },
        { stateName: "Kentucky" },
        { stateName: "Louisiana" },
        { stateName: "Massachusetts" },
        { stateName: "Maryland" },
        { stateName: "Maine" },
        { stateName: "Michigan" },
        { stateName: "Minnesota" },
        { stateName: "Missouri" },
        { stateName: "Mississippi" },
        { stateName: "Montana" },
        { stateName: "North Carolina" },
        { stateName: "North Dakota" },
        { stateName: "Nebraska" },
        { stateName: "New Hampshire" },
        { stateName: "New Jersey" },
        { stateName: "New Mexico" },
        { stateName: "Nevada" },
        { stateName: "New York" },
        { stateName: "Ohio" },
        { stateName: "Oklahoma" },
        { stateName: "Oregon" },
        { stateName: "Pennsylvania" },
        { stateName: "Puerto Rico" },
        { stateName: "Rhode Island" },
        { stateName: "South Carolina" },
        { stateName: "South Dakota" },
        { stateName: "Tennessee" },
        { stateName: "Texas" },
        { stateName: "Utah" },
        { stateName: "Virginia" },
        { stateName: "Virgin Islands" },
        { stateName: "Vermont" },
        { stateName: "Washington" },
        { stateName: "Wisconsin" },
        { stateName: "West Virginia" },
        { stateName: "Wyoming" }
    ],
    Myanmar: [
        {stateName: "Ayeyarwady Region"},
        {stateName: "Bago Region"},
        {stateName: "Chin State"},
        {stateName: "Kachin State"},
        {stateName: "Kayah State"},
        {stateName: "Kayin State"},
        {stateName: "Magway Region"},
        {stateName: "Mandalay"},
        {stateName: "Mon State"},
        {stateName: "Nay Pyi Daw"},
        {stateName: "Rakhine State"},
        {stateName: "Shan State"},
        {stateName: "Tanintharyi Region"},
        {stateName: "Yangon"}
    ]
};
